### ISSUE TITLE
Should not be Slack-only

### ISSUE THREAD

**Issue by dansmithy** [atomist-skills/github-notifications-skill#12]
@cdupuis Can we please change the requirement on this from `SlackResourceProvider` to `ChatProvider` ?

Once web-app changes are deployed, this should result in no change until a second chat provider is available publicly.

**Comment by cdupuis** [comment]
What about copy changes in the README https://github.com/atomist-skills/github-notifications-skill#before-you-get-started? Do we know what the standard text should be instead of Slack only?
