### ISSUE TITLE
Clean up command intents in help

### ISSUE THREAD

**Issue by jrday** [atomist-skills/github-notifications-skill#25]
@cdupuis I recall that there was a limitation preventing this. These are all known, so is there a way for us to fix this listing now?

<img width="667" alt="Screen Shot 2020-08-11 at 3 37 28 PM" src="https://user-images.githubusercontent.com/774714/89955942-f787f700-dbe8-11ea-84d8-0a8666680c4e.png">

**Comment by cdupuis** [comment]
That listing is generated by the bot. I’m not sure if did anything to address this cc @slimslenderslacks
