### ISSUE TITLE
Support full arguments passed into chat commands

### ISSUE THREAD

**Issue by jrday** [atomist-skills/github-notifications-skill#26]
For example, `@atomist link repo` invokes the flow to capture the repo name/slug ...

<img width="353" alt="Screen Shot 2020-08-11 at 4 12 02 PM" src="https://user-images.githubusercontent.com/774714/89957915-8565e100-dbed-11ea-9a53-76402615bd69.png">

... but if I already know it and just want to pass it in, I can't:

<img width="593" alt="Screen Shot 2020-08-11 at 4 11 55 PM" src="https://user-images.githubusercontent.com/774714/89957977-a62e3680-dbed-11ea-807a-67914ac88bbc.png">

Not sure if this issue is a bot issue or specific to this skill.

**Comment by cdupuis** [comment]
That is generally supported in the skill already. This command doesn't take any parameters right now (only mapped parameters; which isn't helpful here but that's the reason you're seeing this).

Perhaps worth re-writing this issue to allow parameters for `link repo`?

**Comment by cdupuis** [comment]
@jrday do you still want this to happen? See my last question please.
