### ISSUE TITLE
Simplify adding custom emoji

### ISSUE THREAD

**Issue by jrday** [atomist-skills/github-notifications-skill#28]
It looks like there is only an [API for adding emoji in Enterprise Grid](https://api.slack.com/methods/admin.emoji.add) but can we run the [`atomist-emojis.bash`](https://static.atomist.com/atomist-emojis.bash) script as the bot user, or is that not something a bot/app can do?

/cc @slimslenderslacks

**Comment by slimslenderslacks** [comment]
@jrday the last we checked, this required the `admin.teams:write` scope, and our app does not request that.  Most users that authorize Atomist will have the permission to add custom emojis on their team (I think most non-guest users can add emojis by default), so it's really just about the scoping.  As is often the case, this scope is quite broad and would grant our app access to other apis (like setName setIcon setDefaultChannel) that we'd prefer our app not be able to access.  The achilles heal of OAuth, isn't it?

So, I think we could probably run this, but we'd have to extend our OAuth scopes.  It would be worth testing with our staging app.
