### ISSUE TITLE
Force only a single configuration of this skill

### ISSUE THREAD

**Issue by jrday** [atomist-skills/github-notifications-skill#3]
Will allowing users to create multiple configurations of this skill in a single workspace cause problems? Unless there is a good use case (that works) to have multiple configurations, it would be best to only allow a single config.

And similarly, if a user can only have a single config of the skill, we could lock the skill name to the default and not allow it to be changed.

**Comment by cdupuis** [comment]
This has been fixed in fbec30fce53bd3e311550155f9c84358d78b0747
